version: '3.9'
services:
  app:
    container_name: resume_builder_frontend_app
    tty: true
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - .:/app
